### ISSUE TITLE
automata_IO.py", line 114, in dfa_dot_importer     g = pydot.graph_from_dot_file(input_file)[0]

### ISSUE THREAD

**Issue by aymeric75** [Oneiroe/PySimpleAutomata#7]
Hi,

From this code:

`from PySimpleAutomata import DFA, automata_IO

dfa_example = automata_IO.dfa_dot_importer("DFA_Hanoi_4_4.dot")

new_dfa=DFA.dfa_reachable(dfa_example)

automata_IO.dfa_to_dot(new_dfa, 'DFA-Hanoi-4-4', './')`

(see .dot file attached as a txt 
[DFA_Hanoi_4_4.txt](https://github.com/Oneiroe/PySimpleAutomata/files/14802332/DFA_Hanoi_4_4.txt)
, I had to reformat it to avoid an error (see other Issue))

I get this error:
```

  File "/workspace/pddlgym-tests/pddlgym/genGraph.py", line 4, in <module>
    dfa_example = automata_IO.dfa_dot_importer("DFA_Hanoi_4_4.dot")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/latplan/lib/python3.11/site-packages/PySimpleAutomata/automata_IO.py", line 114, in dfa_dot_importer
    g = pydot.graph_from_dot_file(input_file)[0]
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

Thanks

**Comment by Oneiroe** [comment]
I respond here also for the [previously pointed error](https://github.com/Oneiroe/PySimpleAutomata/issues/5#issuecomment-2026915988) with this Hanoi example, because they are linked.

First, in the txt/dot file you forgot to quote the name of the initial state with the _fake_ transition:
`fake -> "peg1:default: [d3:default], peg2:default: [d1:default], peg3:default: [d2:default], peg4:default: [d4:default]" [style=bold]`
Second, the problem in both cases is the colon (":") character in the name of the states in the input automaton. I do not know why, but the graphviz library does not handle it properly during the rendering of the graph. Quick fix: remove this character and everything works.
 
Nevertheless it takes quite some time to generate the graphical SVG result. Having such long names for the states hampers not only the performance, but also the readability of the graphical representation of the automaton. Consider the option of encoding these names with shorted codes.

**Comment by aymeric75** [comment]
Indeed I removed the ":" caracters and it works thanks
